// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJG4jcfttS8UbTEYQ3SEmfKpqj25hT1NM',
    appId: '1:774780104370:web:f1362beabd29559d6063ab',
    messagingSenderId: '774780104370',
    projectId: 'bukidlink-e85f7',
    authDomain: 'bukidlink-e85f7.firebaseapp.com',
    storageBucket: 'bukidlink-e85f7.firebasestorage.app',
    measurementId: 'G-KCJCTWDGS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqSo2T0zWgCA-U7_IkLeSXS3T9DV6-vsY',
    appId: '1:774780104370:android:cd7faa74fc3528e06063ab',
    messagingSenderId: '774780104370',
    projectId: 'bukidlink-e85f7',
    storageBucket: 'bukidlink-e85f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqyNdgLjHxXrCwasYT3kxQzkrBHs75ZVc',
    appId: '1:774780104370:ios:5d2aed3d623c19c16063ab',
    messagingSenderId: '774780104370',
    projectId: 'bukidlink-e85f7',
    storageBucket: 'bukidlink-e85f7.firebasestorage.app',
    androidClientId: '774780104370-ud9fhqsni7gm0teanf8b6ncq0nido7lt.apps.googleusercontent.com',
    iosClientId: '774780104370-40ksqrid7mrp14cit3bsv90r7o12tpcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bukidlink',
  );

}